"""Convert time fields to DateTime and cleaning

Revision ID: 266343da7b4a
Revises: 251d1235bb52
Create Date: 2026-02-20 02:26:44.873516

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "266343da7b4a"
down_revision: str | Sequence[str] | None = "251d1235bb52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "earthquakes",
        "time",
        existing_type=sa.BIGINT(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="to_timestamp(time / 1000.0)",
        existing_nullable=False,
    )
    op.alter_column(
        "earthquakes",
        "updated",
        existing_type=sa.BIGINT(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="to_timestamp(updated / 1000.0)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("earthquakes", "updated", existing_type=sa.DateTime(), type_=sa.BIGINT(), existing_nullable=False)
    op.alter_column("earthquakes", "time", existing_type=sa.DateTime(), type_=sa.BIGINT(), existing_nullable=False)
    # ### end Alembic commands ###
