"""Initial migration

Revision ID: a42081615b36
Revises:
Create Date: 2026-02-20 02:04:01.447013

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a42081615b36"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earthquakes",
        sa.Column("mag", sa.Float(), nullable=True),
        sa.Column("place", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("tz", sa.Integer(), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("detail", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tsunami", sa.Integer(), nullable=True),
        sa.Column("sig", sa.Integer(), nullable=True),
        sa.Column("net", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("ids", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("sources", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("types", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nst", sa.Integer(), nullable=True),
        sa.Column("dmin", sa.Float(), nullable=True),
        sa.Column("rms", sa.Float(), nullable=True),
        sa.Column("gap", sa.Float(), nullable=True),
        sa.Column("magType", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("felt", sa.Integer(), nullable=True),
        sa.Column("cdi", sa.Float(), nullable=True),
        sa.Column("mmi", sa.Float(), nullable=True),
        sa.Column("alert", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("depth", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_earthquakes_time"), "earthquakes", ["time"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_earthquakes_time"), table_name="earthquakes")
    op.drop_table("earthquakes")
    # ### end Alembic commands ###
